name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release-windows:
    name: Build & Release (Windows)
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build Windows binary
        run: cargo build --release --target x86_64-pc-windows-msvc

      - name: Prepare release package
        run: |
          mkdir release
          copy README.md release\
          copy target\x86_64-pc-windows-msvc\release\magnet.exe release\
          powershell Compress-Archive -Path release\* -DestinationPath magnet-${{ github.ref_name }}-windows-x86_64.zip
        shell: cmd

      - name: Show files for debug
        run: dir
        shell: cmd

      - name: Upload compiled binary to release
        uses: softprops/action-gh-release@v2
        with:
          files: magnet-${{ github.ref_name }}-windows-x86_64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
